### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Jacxk** [ruany/LiteBansAPI#7]
Hey there, I was wondering if could you add a way to get the punished player.
I'm creating a discord bot which will send a message saying that a player was banned to a channel but there is no way to get that player right now.
Thanks for your time.

**Comment by ruany** [comment]
The api provides Entry.getUuid() which is the punished player's UUID.
To determine the player's name you have to figure that out yourself, for example, by querying Mojang or the history table.
LiteBans does not store punished player names in punishment entries, because it is not a name banning plugin.
